input:
  trigger_key: "F12"

obs:
  executable_path: "C:/Program Files/obs-studio/bin/64bit/obs64.exe"
  websocket:
    host: "localhost"
    port: 4455
    timeout_seconds: 30
  scene_name: "SDVX PlayLog Tool"

result_detection:
  threshold: 0.85
  interval_seconds: 1.0
  scale: 1.0
  region:
    x: 1666
    y: 584
    width: 116
    height: 462

song_start_detection:
  threshold: 0.85
  interval_seconds: 1.0
  scale: 1.0
  region:
    x: 572
    y: 155
    width: 150
    height: 765

ocr:
  regions:
    song_name:
      x: 387
      y: 995
      width: 530
      height: 32

    artist:
      x: 387
      y: 1030
      width: 530
      height: 32

    difficulty_level:
      x: 50
      y: 865
      width: 148
      height: 41

    clear_type:
      x: 464
      y: 925
      width: 610
      height: 65

    rate_type:
      x: 726
      y: 1197
      width: 197
      height: 23

    score:
      x: 427
      y: 1065
      width: 380
      height: 60

    score_delta:
      x: 816
      y: 1102
      width: 141
      height: 17

    ex_score:
      x: 529
      y: 1142
      width: 96
      height: 25

    ex_score_delta:
      x: 897
      y: 1154
      width: 88
      height: 17

play_log:
  min_score: 9000000
